export const products = [
    {
        id: 1,
        title: 'Yellow Pail',
        description: 'On-demand sand castle construction expertise.',
        url: '#',
        votes: 23,
        submitterAvatarUrl: '%PUBLIC_URL%/assets/img/avatars/daniel.jpg',
        productImageUrl: '%PUBLIC_URL%/assets/img/products/image-aqua.png',
    },
    {
        id: 2,
        title: 'Supermajority: The Fantasy Congress League',
        description: 'Earn points when your favorite politicians pass legislation.',
        url: '#',
        votes: 12,
        submitterAvatarUrl: '%PUBLIC_URL%/assets/img/avatars/kristy.png',
        productImageUrl: '%PUBLIC_URL%/assets/img/products/image-rose.png',
    },
    {
        id: 3,
        title: 'Tinfoild: Tailored tinfoil hats',
        description: 'We already have your measurements and shipping address.',
        url: '#',
        votes: 3,
        submitterAvatarUrl: '%PUBLIC_URL%/assets/img/avatars/veronika.jpg',
        productImageUrl: '%PUBLIC_URL%/assets/img/products/image-steel.png',
    },
    {
        id: 4,
        title: 'Haught or Naught',
        description: 'High-minded or absent-minded? You decide.',
        url: '#',
        votes: 6,
        submitterAvatarUrl: '%PUBLIC_URL%/assets/img/avatars/molly.png',
        productImageUrl: '%PUBLIC_URL%/assets/img/products/image-yellow.png',
    },
];
